#!/bin/bash
echo -e 'count-Invalid Username'
grep 'Invalid user' /var/log/auth.log | sudo awk 'match($0, /[A-Za-z]+ from [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/) {print substr($0, RSTART, RLENGTH)}' | sudo awk 'match($0, /^[A-Za-z]+/) {print substr($0,RSTART,RLENGTH)}' | sort -n | uniq -c | sed -e 's/^[ \t]*//'