#!/bin/bash
echo -e 'Invalid User - IP Address'
grep 'Invalid user' /var/log/auth.log | sudo awk 'match($0, /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/) {print substr($0, RSTART, RLENGTH)}'| sort -n | uniq -c | sed -e 's/^[ \t]*//'