#!/bin/bash
echo -e 'Authentication Failure for root\nNumAttempts-IP Address'
grep 'authentication failure' /var/log/auth.log | sudo awk 'match($0,/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/) {print substr($0, RSTART, RLENGTH)}' /var/log/auth.log | sort -n | uniq -c | sed -e 's/^[ \t]*//'